### ISSUE TITLE
Error occurred in react-select

### ISSUE THREAD

**Issue by lvitaly** [payalabs/scalajs-react-bridge#12]
Hi Ramnivas,
I've already posted same issue.
> I've tried to use [react-select](https://github.com/JedWatson/react-select) component through react bridge but got errors.
> ```
Uncaught Error: Cannot find module 'react-dom'
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ItemsPage`.
Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `ItemsPage`.
Uncaught TypeError: Cannot read property 'remove' of undefined
```
>I've created [repo with example](https://github.com/lvitaly/scalajs-react-select-example) for easy reproduce.

You've closed issue with comment
>I tried the example app you provided. I am getting the same error even when I remove the scalajs-react-bridge dependency (along with the Select component). So the issue seems to be with how react dependencies are pulled in and not with scalajs-react-bridge. I don't have much experience with js dependencies through build.sbt (I use webpack instead as shown in https://github.com/payalabs/scalajs-react-bridge-example).
>
>I am closing the issue since it seems unrelated to scalajs-react-bridge.

I followed your comment and fix js dependency error but I still get errors on wrong react element creation.
```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ItemsPage`.
Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `ItemsPage`.
```

Maybe you can help me with this. Sample repo was updated.

**Comment by lvitaly** [comment]
I've found out.

If main.js contains row
```js
ReactSelect = require("react-select");
```

and Select component declares like this
```scala
object ReactSelect {

  def apply(name : UndefOr[String] = undefined) = {

    val toJS = {
      val p = js.Dynamic.literal()
      name.foreach(v => p.updateDynamic("name")(v))
      p
    }

    val f = React.asInstanceOf[js.Dynamic].createFactory(js.Dynamic.global.ReactSelect)
    f(toJS).asInstanceOf[ReactComponentU_]
  }

}
```

then Select component will create without errors.

Seems that bridge is occurred mismatch error of `ReactSelect = require("react-select")` and `js.Dynamic.global.ReactSelect`.

**Comment by ramnivas** [comment]
That makes sense. As described in https://github.com/payalabs/scalajs-react-bridge#defining-components, the bridge expects the class name to match the one exported in JS.

There is an issue for this https://github.com/payalabs/scalajs-react-bridge/issues/3. So I am closing this one (but feel free to reopen if I misunderstood something).
