### ISSUE TITLE
Immutable Seqs aren't converted

### ISSUE THREAD

**Issue by codingismy11to7** [payalabs/scalajs-react-bridge#15]
Ran into an issue when eradicating `scala.collection.Seq` from the codebase in favor of `scala.collection.immutable.Seq` after seeing mutable structures being passed around. Turns out the immutable seq wasn't being `JsWriter.toJs`d, changing it to a `js.Array` meant that the values inside the array/seq weren't being `toJs`d, so had to declare the field in the wrapper as being explicitly a `scala.collection.Seq`. Would be nice to have a `JsWriter` for immutable Seqs

**Comment by ramnivas** [comment]
Fixed via 587f2856abcc2298190bd2ba91858504fde2f7e0

Can you locally build this and test it with your code. I will be releasing 0.3.0 soon so it will be nice to get a confirmation.

**Comment by codingismy11to7** [comment]
:+1:  looks good here
