### ISSUE TITLE
sbt unresolved dependency 

### ISSUE THREAD

**Issue by richbirch** [payalabs/scalajs-react-bridge#18]
Hi

Is it still possible to use this project? sbt doesn't like the documented way to include it:

sbt.ResolveException: unresolved dependency: com.payalabs#scalajs-react-bridge_sjs0.6_2.11;0.4.0-SNAPSHOT: not found

**Comment by ramnivas** [comment]
Did you add:
`resolvers += Resolver.sonatypeRepo("snapshots")`

Please try and let me know how it goes.

**Comment by richbirch** [comment]
Hi

Thanks for the quick response. I do in fact already have sonatype resolver in the project.

When I search https://search.maven.org nothing comes up for your project. Could it have been removed some how?

**Comment by ramnivas** [comment]
Do you have the *snapshot* Sonatype in your resolvers? The artifacts are there: https://oss.sonatype.org/content/repositories/snapshots/com/payalabs/scalajs-react-bridge_sjs0.6_2.12/0.4.0-SNAPSHOT/

**Comment by nafg** [comment]
Worked for me... @richbirch can this issue be closed?

**Comment by richbirch** [comment]
I'm getting this:

```
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/payalabs/scalajs-react-bridge_sjs0.6_2.11/0.4.0-SNAPSHOT/scalajs-react-bridge_sjs0.6_2.11-0.4.0-SNAPSHOT.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.payalabs#scalajs-react-bridge_sjs0.6_2.11;0.4.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

```
