### ISSUE TITLE
Provide JsWriter for the union type

### ISSUE THREAD

**Issue by Semptic** [payalabs/scalajs-react-bridge#26]
I tried the last few hours to get a `JsWriter[A | B]` working, but without any success. Maybe someone else got an idea?

**Comment by ramnivas** [comment]
I believe you are looking for https://github.com/payalabs/scalajs-react-bridge/commit/7985ce722347309120fc41ae78e9a2bad6ef9687

**Comment by Semptic** [comment]
Yes thank you!
