### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by cranst0n** [payalabs/scalajs-react-bridge#27]
Any chance for a new release? There's been quite a few additions and I've found myself needing to patch in stuff that already exists since the last one.

**Comment by ramnivas** [comment]
Done!

https://oss.sonatype.org/content/groups/public/com/payalabs/scalajs-react-bridge_sjs0.6_2.12/0.5.0/ and https://oss.sonatype.org/content/groups/public/com/payalabs/scalajs-react-bridge_sjs0.6_2.11/0.5.0/
