### ISSUE TITLE
withKey

### ISSUE THREAD

**Issue by cranst0n** [payalabs/scalajs-react-bridge#28]
Maybe I'm being a little dense but should we be able to set the key for a given component as shown in the [scala-js-react docs](https://github.com/japgolly/scalajs-react/blob/fb95f0ee387dd5d52a41439c8c04021795d70777/doc/USAGE.md#keys)? Can't seem to get anything working.

**Comment by ramnivas** [comment]
You can pass the key as a regular property just as you would in React itself (as shown in the `TagsInput` example in README).

**Comment by cranst0n** [comment]
Ah sorry. Not sure how I missed that. Thanks!
