### ISSUE TITLE
ScalaJsReact 1.2.0

### ISSUE THREAD

**Issue by cranst0n** [payalabs/scalajs-react-bridge#29]
[scalajs-react v1.2.0](https://github.com/japgolly/scalajs-react/blob/master/doc/changelog/1.2.0.md) has a number of API changes that appear to be breaking for this tool. Supporting the new version would be awesome.

**Comment by ramnivas** [comment]
I am currently swamped with other activities. A PR to make this happen is welcome.

**Comment by cranst0n** [comment]
It appears @jac3km4 has beaten me to the punch (#30)! :tada:

**Comment by ramnivas** [comment]
Fixed by #31
