### ISSUE TITLE
configurable name for component 

### ISSUE THREAD

**Issue by chandu0101** [payalabs/scalajs-react-bridge#3]
having same name as js component will leads to confusion !
example :
material ui expose a component TextField , as TextField is generic we must check package while importing :s , i prefer adding a prefix/suffix  MuiTextField

i see you have config for name space instead of that let the user define final name ( namespace.jsname= mui.TextField / ReactTags) ?

**Comment by ramnivas** [comment]
Agree. I felt the same when creating, for example, `TagsInput` vs. `ReactMediumEditor`. I would have liked to drop "React" from the latter. It is a somewhat different use case than you present, but the same logic will help in both.

What do you think of the following:

1. (This will help when creating a set of related components such as Mui). Add `addPrefix` and `dropPrefix` to [`ComponentNamespace`](https://github.com/payalabs/scalajs-react-bridge/blob/master/src/main/scala/com/payalabs/scalajs/react/bridge/ComponentNamespace.scala) with default set to empty string. `addPrefix` is something we add on the underlying function name, whereas `dropPrefix` is we drop when calculating the underlying function name (underlying function name = classname + addPrefix - dropPrefix). So, in the Mui case, you will have something like this:
 ```
@ComponentNamespace(dropPrefix = "Mui")
class MuiBridgeComponent extends ReactBridgeComponent

case class MuiTextField(...) extends MuiBridgeComponent
// Drops "Mui" due to annotation from the base class 
// and thus binds to the underlying "TextField" function
```

2. (This helps when customizing one component at a time). Add `@ComponentName` annotation that can be specified on leaf components (such as `MuiTextField`) that will use whatever is specified there as the underlying component function (overriding anything that may have been specified with a `@ComponentNamespace` in a base class).
 ```
@ComponentName("ReactMediumEditor")
case class MediumEditor(...) extends ReactBridgeComponent
```

WDYT?

**Comment by chandu0101** [comment]
i liked second option , and how about name space ? 
```scala
@ComponenetName("mui.TextField")
case class MuiTextField 

@ComponentName("ReactDraggable")
case class ReactDraggable 

```
is this what u are going to suggest ... ?

**Comment by ramnivas** [comment]
I meant we will implement both options! The first one will help when you want Scala classes to carry and additional prefix (scala `MuiTextField` -> js `TextField`)--you will make such a decision in a common base class (as I do with `ReactBootStrap`). The second will help when porting one component from a library (such as `ReactMediumEditor`).

**Comment by chandu0101** [comment]
oh ok :)

**Comment by ramnivas** [comment]
Fixed with the latest implementation that allows overriding `componentName` and/or `componentNamespace`
