### ISSUE TITLE
() => Unit as Callback

### ISSUE THREAD

**Issue by Daxten** [payalabs/scalajs-react-bridge#34]
Hi,
maybe I'm doing this wrong, but I think only this works:

     onClose: () => Callback

and not this:

     onClose: Callback

imo the second variant would be nice to have

**Comment by ramnivas** [comment]
This used to be possible, but not anymore. See https://github.com/payalabs/scalajs-react-bridge/commit/13ea6e48527c63a9d28519778d68c7a117efff4a.

If you can think of some way to support plain `Callback`s, please make a PR.

**Comment by ramnivas** [comment]
Closing the issue. Feel free to reopen if needed.
