### ISSUE TITLE
Declare render functions

### ISSUE THREAD

**Issue by rpiaggio** [payalabs/scalajs-react-bridge#35]
First of all, thank you for this great library!

I am trying to use it to declare a facade for https://github.com/moroshko/react-autosuggest. One of the properties of this component (`renderSuggestion`) is a render function, which should return a React component. I tried declaring it as a function `(...) => CallbackTo[VdomNode]`, but when I do this I get a compilation error: `value toJs is not a member of <notype>` on the `autoNoChildren` macro.

Is this functionality supported? If so, how should I declare this property?

Thank you!

**Comment by ramnivas** [comment]
Welcome!

I think you need to declare the function as `(...) => VdomElement`.

**Comment by rpiaggio** [comment]
Thank you @ramnivas , that works!
