### ISSUE TITLE
Publish for scalajs 1.0

### ISSUE THREAD

**Issue by nafg** [payalabs/scalajs-react-bridge#46]

**Comment by nafg** [comment]
I guess this is blocked on https://github.com/japgolly/scalajs-react/issues/599

**Comment by ramnivas** [comment]
That and we need to cross-publish for 0.6 and 1.0, so need build config changes for that. Could you do a PR for that?

**Comment by nafg** [comment]
scalajs-react is now cross-published for scalajs 0.6 and 1.0, released as 1.7.0

**Comment by nafg** [comment]
https://github.com/japgolly/scalajs-react/blob/master/doc/changelog/1.7.0.md

**Comment by nafg** [comment]
You don't _need_ to cross-publish. You could (optionally) publish one version as the last 0.6 version, and do a major version bump that drops 0.6 and uses 1.0 instead.

Unless you have downstream libraries that cross-publish, or have another reason.

**Comment by ramnivas** [comment]
I think it may be best to cross-publish it for the time being.

**Comment by nkgm** [comment]
Has this been published yet? Not seeing any `sjs1` artifacts thus far.
