### ISSUE TITLE
Allow scala seq/maps as callback function parameters

### ISSUE THREAD

**Issue by ramnivas** [payalabs/scalajs-react-bridge#5]
Currently, we transform `Seq` and `Map` parameters to case classes to `js.Array` and literal, but still require parameters to callback functions to be of js types (see [`onChange` of TagsInput](https://github.com/payalabs/scalajs-react-bridge-example/blob/master/src/main/scala/com/payalabs/scalajs/react/bridge/elements/TagsInput.scala#L12) for example). It will be nice to allow callbacks to specify normal Scala types.

**Comment by ramnivas** [comment]
Here is an outline of how we might do it. Given a component with the following as one of its case class parameter:

```
onChange: js.UndefOr[Seq[String] => Unit] = js.undefined
```
The macro will create a js properties to be set for the underlying component:

```
onChangeJs : js.Array[String] => Unit = arr => {
  onChange(Seq(arr.map(e => elementReader.fromJs(e)): _*)
}
```

Essentially, we transform the argument with code that is a dual of https://github.com/payalabs/scalajs-react-bridge/blob/8bc3b80e2daab1ad941779bb0803a6a4487afd6b/src/main/scala/com/payalabs/scalajs/react/bridge/package.scala#L21.

**Comment by ms-ati** [comment]
Any progress on this?

**Comment by ramnivas** [comment]
Unfortunately, I haven't had a chance to work on this.
