### ISSUE TITLE
Publish new version with sjs1 support.

### ISSUE THREAD

**Issue by mikla** [payalabs/scalajs-react-bridge#82]
Hi, 

I see that https://github.com/payalabs/scalajs-react-bridge/issues/46 is merged quite a while ago.

Could you please consider having a release with these changes? 

Thanks in advance!

**Comment by ramnivas** [comment]
Published 0.8.4.

**Comment by arixmkii** [comment]
@ramnivas Artifacts can't be resolved from any of default repositories. Also, not available in maven central index (web interface). Should one add some third-party repos before using version 0.8.4?

**Comment by ramnivas** [comment]
Unsure what happened, but I have released 0.8.5 and it is now available https://mvnrepository.com/artifact/com.payalabs/scalajs-react-bridge_sjs1_2.13/0.8.5.
