### ISSUE TITLE
Provide interoperability with scalajs-react extras

### ISSUE THREAD

**Issue by lvitaly** [payalabs/scalajs-react-bridge#9]
Bridge doesn't have possibilities to use scalajs-react MonocleReact/ScalazReact without workarounds.

**Comment by ramnivas** [comment]
Can you explain a bit more? Perhaps some code snippet of what you will like to work and doesn't will help.

**Comment by lvitaly** [comment]
Sorry that I've posted issue without additional information...
Here is examples of how to use MonocleReact extention.
This is scalajs-react snippet
```scala
ReactComponentB[ExternalVar[String]]("NameInput")
  .render{ evar =>
    def updateName = (e: ReactEventI) => evar.set(e.target.value)

    <.input(
      ^.`type` := "text",
      ^.value := evar.value,
      ^.onChange ~~> updateName
    )
  }
```
Here is same functionality in scalajs-react-bridge
```scala
ReactComponentB[ExternalVar[String]]("NameInput")
  .render{ evar =>
    def updateName(event: ReactEventI): Unit = evar.set(event.target.value).unsafePerformIO()
        
    Input(
      `type` = "text",
      labelClassName = "col-xs-2",
      wrapperClassName = "col-xs-10",
      label = _label,
      value = evar.value,
      onChange = updateName _
    )()
  }
```
So if I try to use MonocleReact extention in react-bridge component then I shuld call unsafe method to perform IO. In case of scalajs-react `~~>` is implisite function from `japgolly.scalajs.react.ScalazReact._` for perform same goal.
This is not a big deal and I undertand that it could be done by self written implicite function but I think would be great to support this kind of interoperability.
What do you think?

**Comment by lvitaly** [comment]
Something like this
```scala
implicit val bridgeIO: (ReactEventI => IO[Unit]) => js.UndefOr[ReactEventI => Unit] = {
  func =>
    val _func: ReactEventI => Unit = func(_).unsafePerformIO()
    _func.asInstanceOf[js.UndefOr[ReactEventI => Unit]]
}

ReactComponentB[ExternalVar[String]]("NameInput")
  .render{ evar =>
    def updateName = (e: ReactEventI) => evar.set(e.target.value)

    Input(
      `type` = "text",
      labelClassName = "col-xs-2",
      wrapperClassName = "col-xs-10",
      label = _label,
      value = evar.value,
      onChange = updateName _
    )()
  }
```

**Comment by ramnivas** [comment]
I see and thanks for providing a clear example. I think the implicit conversion you provided sound like a good idea, and since that code doesn't depend on Monocle etc., adding it to scalajs-react-bridge should not be an issue (otherwise a separate module or some other dependency management technique will be needed to avoid impacting users that don't use Monocle).

I am likely to find some time later this week/weekend to look into scalajs-react-bridge issues (this and other). But if you can make a PR (ideally along with a test(s)), that will be awesome.

**Comment by ramnivas** [comment]
With `IO` removed from scalajs-react in 0.10.x and I have just added support for functions that return `Callback`, I think this is no longer needed. Please reopen if needed.
